<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>TravelInfoAssistant.Api</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference IncludYOH“ZXÜ›ÜÛÙ‘^[œÚ[ÛœËØXÚ[™Ë”ÝXÚÑ^Ú[™ÙT™Y\Èˆ™\œÚ[ÛHŒLŒŒLˆˆÏ‚ˆXÚØYÙT™Y™\™[˜ÙH[˜ÛYOH“œÜÜ[‘[]Qœ˜[Y]ÛÜšÐÛÜ™K”ÜÝÜ™TÔSˆ™\œÚ[ÛHŒLŒŒÈˆÏ‚ˆXÚØYÙT™Y™\™[˜ÙH[˜ÛYOH”ÝØ\ÚXÚÛK\Ü™]ÛÜ™Hˆ™\œÚ[ÛHŒLŒ‹ŒÈˆÏ‚ˆÒ][QÜ›Ý\‚‚ˆ][QÜ›Ý\‚ˆÛÛ[\]OH‘]KØZ\œÜË›Z[‹šœÛÛˆˆÛÜUÓÝ]]\™XÝÜžOH”™\Ù\™S™]Ù\ÝˆÏ‚ˆÒ][QÜ›Ý\‚Ô›Ú™XÝ‚